### ISSUE TITLE
Pinch to zoom and fit options from newpipe

### ISSUE THREAD

**Issue by Rihcus** [VueTubeApp/VueTube#118]
**Is your feature request related to a problem? Please describe.**
Pinch to zoom and fit options from newpipe

**Describe the solution you'd like**
![Screenshot_20220319-132808_NewPipe_SponsorBlock](https://user-images.githubusercontent.com/30292597/159131872-da847828-5000-426c-8b5a-cb047c20a11d.png)
Standard view

![Screenshot_20220319-132818_NewPipe_SponsorBlock](https://user-images.githubusercontent.com/30292597/159131903-8a50b7e1-acd1-4754-9f73-85e046eff39e.png)
Fit mode

![Screenshot_20220319-132818_NewPipe_SponsorBlock](https://user-images.githubusercontent.com/30292597/159131919-5058bb26-930e-487b-ac43-71173aecb4d5.png)
Zoom mode

**Describe alternatives you've considered**
Newpipe and the stock youtube app

**Additional context**

**Comment by Rihcus** [comment]
![Screenshot_20220319-133514_NewPipe_SponsorBlock](https://user-images.githubusercontent.com/30292597/159132104-1529c247-9e62-4a5c-bdd1-e7a0e07a712d.png)

![Screenshot_20220319-133524_NewPipe_SponsorBlock](https://user-images.githubusercontent.com/30292597/159132118-32f02c0a-e29f-4ded-aa3e-3d7e846c17e8.png)
![Screenshot_20220319-133612_NewPipe_SponsorBlock](https://user-images.githubusercontent.com/30292597/159132140-73c79773-f803-40df-8d59-88996d3d4a63.png)
![Screenshot_20220319-133623_NewPipe_SponsorBlock](https://user-images.githubusercontent.com/30292597/159132146-81dde4e7-c4f9-4e5e-9610-7e693117f319.png)
![Screenshot_20220319-133702_NewPipe_SponsorBlock](https://user-images.githubusercontent.com/30292597/159132167-8252ae65-af2f-47fe-820a-69abf02daf70.png)

**Comment by Svk1190** [comment]
Might be related to #36.

**Comment by PickleNik** [comment]
basic pinch to zoom by height works, other modes will come from #36 implementation.
