### ISSUE TITLE
release on github releases

### ISSUE THREAD

**Issue by JacksonChen666** [VueTubeApp/VueTube#17]
**Is your feature request related to a problem? Please describe.**
i (e.g. some average normie user) don't know where i should go download the thing

i heard that i need to go on the discord server to download the releases

i (e.g. some user) would need to sign up for discord to join the server to even download this thing.

too many unnecessary services to sign up to to even download this thing. tbh it can be better (it can be 0).

**Describe the solution you'd like**
create github releases

**Describe alternatives you've considered**
git tagging and taking output from the github action (possible it will require a github account)

**Additional context**
![discord server with releases](https://user-images.githubusercontent.com/50755746/158081514-810fc9c5-8105-4c4c-bf18-c274c90b4d58.png)

**Comment by Frontesque** [comment]
There used to be releases under GitHub releases but we update so quickly because it's still under development that there is almost no point. When we get something more complete, then sure.

**Comment by humble-barnacle001** [comment]
@Frontesque could you consider realising automatically via GitHub actions?

**Comment by JacksonChen666** [comment]
@Frontesque add this to some milestone like a stable release milestone so you won't forget

**Comment by ArjixWasTaken** [comment]
> > @Frontesque could you consider realising automatically to GitHub release via GitHub actions?
> 
> you can already download the automatic builds from the actions tab

you can only download artifacts if you are logged in, so this is inconvenient if say you try to download it from a new device, and you are not logged in to github

it is not hard at all to set it up to publish the artifacts as prereleases automatically, I can even make that a PR if you want me to

**Comment by pekempy** [comment]
> it is not hard at all to set it up to publish the artifacts as prereleases automatically, I can even make that a PR if you want me to

Yes but there's little point in settings this up when there are commits every few minutes or so. Once there's a more fledged app with some features it might be worth doing but not rn

**Comment by PickleNik** [comment]
@Frontesque @404-Program-not-found I suppose this can be closed as completed
