### ISSUE TITLE
Gestures to Fullscreen In/Out

### ISSUE THREAD

**Issue by ghost** [VueTubeApp/VueTube#193]
Hi.

YouTube stock client allows to maximize and minimize player through gestures (performing on player).

- From halfscreen...swipe to up to maximize in fullscreen.
- From fullscreen...swipe to bottom to minimize in halfscreen.

**Comment by RadiusGauge** [comment]
Uploading Screen_Recording_20220326-180509.mp4…

**Comment by RadiusGauge** [comment]
https://user-images.githubusercontent.com/102417412/160250141-66b57a02-7b5e-42c1-a258-4b1bdedb5e84.mp4
