### ISSUE TITLE
Double tap to seek

### ISSUE THREAD

**Issue by ghost** [VueTubeApp/VueTube#200]
Hi.

Add the double tap to seek feature on  lateral player edges (with or without fullscreen, in portrait or landscape), with an option to select the time amount to skip (default set on 10 seconds).

**Comment by etekweb** [comment]
Double-tap to seek is functional in latest build, currently skips 10 seconds. There is also an overlay button that skips 5 seconds.

**Comment by 404-Program-not-found** [comment]
thanks for pointing this out! I will be closing this issue
