### ISSUE TITLE
Audio becomes choppy when phone screen is turned off

### ISSUE THREAD

**Issue by ThatOneCalculator** [VueTubeApp/VueTube#201]
**Describe the bug**
When turning my phone off, the audio playing becomes very choppy. The issue doesn't occur anymore after turning it on. 

**To Reproduce**
1. Play video
2. Hit power button

**Device Information**
 - OS: Android 11
 - App Version 798bd5a

**Comment by Frontesque** [comment]
What device are you using? I'm on android 12 but when I turn off my phone screen, playback pauses.

**Comment by ThatOneCalculator** [comment]
OnePlus 7 Pro, Android 11

**Comment by Frontesque** [comment]
> OnePlus 7 Pro, Android 11

does that have miui

**Comment by Frontesque** [comment]
I can't seem to reproduce this

**Comment by Frontesque** [comment]
This doesn't seem to be an issue. Feel free to reopen this if there is still an issue.
