### ISSUE TITLE
Search result visual bug in android tablet interface

### ISSUE THREAD

**Issue by Waylander05** [VueTubeApp/VueTube#205]
![Screenshot_20220328_231831_com Frontesque youtube](https://user-images.githubusercontent.com/99947510/160443381-80137287-ebef-4f43-9bc1-e2d301e86d42.jpg)
I'm not to sure what caused this, but it seems to affect general search term like "Mr bean", "best footballer of all time"

**Comment by Waylander05** [comment]
Yes I already try searched mrbeast and pewdiepie. Channel specific search term seems fine, but it doesn't display multiple rows.
![Screenshot_20220329_002450_com Frontesque youtube](https://user-images.githubusercontent.com/99947510/160453474-7a9747f0-28c2-4f03-b286-d8ef471baec7.jpg)

**Comment by Frontesque** [comment]
Is this still an issue on the latest unstable? https://vuetube.app/install/

**Comment by Waylander05** [comment]
Apologies for the late reply. The issue still happen even in the latest nightly release

**Comment by Frontesque** [comment]
thread closed for inactivity- please reply to reopen if this is still an issue.
