### ISSUE TITLE
Pre-buffer videos

### ISSUE THREAD

**Issue by github59173** [VueTubeApp/VueTube#221]
**Is your feature request related to a problem? Please describe.**
Long loading times for videos to start.

**Describe the solution you'd like**
Pre-buffer videos in the shown list before selecting them so "instant" playback can occur. Youtubes official app seems to do this.

**Describe alternatives you've considered**
I have none at this time.

**Additional context**
Vuetubes current video player/state of the app is slow to start videos upon selection. Proposed solution for the problem can be found above.

**Comment by Frontesque** [comment]
I believe that youtube doesn't prebuffer, but they prefetch the links

**Comment by Svk1190** [comment]
Good idea! But maybe it should be activated only when user is on Wi-Fi, but it will not be activated when user is on mobile data.

There can be a settings page where user can choose settings for Wi-Fi and mobile data:

Setting for WiFi or Mobile Data : 
1) Unrestricted data or restricted data
2) Select default resolution
3) Prefetch video for speedy playback or not
4) Stop/warn when 500 MB data is used per day (customize limit)
