### ISSUE TITLE
Login data fetch

### ISSUE THREAD

**Issue by ghost** [VueTubeApp/VueTube#228]
Hi.

It could be useful to add a way to fetch login data from Play Services (or eventually MicroG), to avoid input them again.

**Comment by Crissomar** [comment]
I think he's talking about some apps that let you login via google play services, but I don't have any idea if the token is only for authentication.
https://developers.google.com/identity/sign-in/android/start-integrating

An alternative could be login using browser with an api key like the youtube kodi addon (showing google accounts on browser)
OR via youtube.com/activate with an activation code just like SmartTubeNext (sponsorblock for android TV) for devices
https://developers.google.com/youtube/registering_an_application?hl=es
