### ISSUE TITLE
Toolbar strip

### ISSUE THREAD

**Issue by ghost** [VueTubeApp/VueTube#247]
Toolbar strip position should start from middle instead of left, such on iOS YouTube client.

![55404251-EA48-4835-9826-AE0656BF1845](https://user-images.githubusercontent.com/102417412/163653971-b17dbec0-b265-4c03-a654-d586ae9a756e.jpeg)

**Comment by PickleNik** [comment]
Was previously implemented but not liked by the community, might be implemented as an option in the future, but the padding has already been increased from what's in the screenshot
