### ISSUE TITLE
Implement channels 

### ISSUE THREAD

**Issue by raluvy95** [VueTubeApp/VueTube#249]
**Describe the bug**
I just installed the latest nightly VueTube. No idea if it's under developement.

**To Reproduce**
1. Open VueTube
2. Click on any videos
3. Click on a channel

**Expected behavior**
The page should display channel's information or show under developement page

**Screenshots**
![Screenshot_20220420-010629_VueTube](https://user-images.githubusercontent.com/43247023/164109654-c1f25b52-a2b6-41fa-8202-35f14cdd8170.jpg)

**Device Information**
 - OS: Android 10
 - App Version: a76f697

**Comment by 404-Program-not-found** [comment]
Expected behaviour - channels have not been implemented yet. Will change the title and tags to better reflect this
