### ISSUE TITLE
[Bug] scrolling far into the comments causes more lag when opening and closing comment page

### ISSUE THREAD

**Issue by nokanol45** [VueTubeApp/VueTube#269]
**Describe the bug**
When opening the comment page, there will be a slight lag, but when you scroll very far into the comments, the lag when opening gets significantly worse.

**To Reproduce**
1. Go to any video
2. Click open the comments, see that there is a slight lag in the animation.
3. Scroll very far down into the comments
4. See that the lag when opening and closing the comment page get significantly worse. It even lags out the player.

**Expected behavior**
No lag in opening and closing the comment page whatsoever

**Recordings**

https://user-images.githubusercontent.com/101823676/167151569-cc0459d3-57ed-4fab-928f-4bfc6cfab246.mp4

**Device Information**
![Screenshot_20220506-221918_VueTube](https://user-images.githubusercontent.com/101823676/167151765-c500648e-c497-458a-aa77-d861b3532996.png)
Text:

**App Information:**
App version: fae8bdd

**Device Information:**
Platform: android
Operating System: android (12)
Model: SM-G9730
Manufacturer: samsung
Emulator: no

**Additional context**
Apparently some devices do not have this issue, please comment below if your device has the issue or not.

**Comment by 404-Program-not-found** [comment]
is this fixed in the latest unstable?

**Comment by nokanol45** [comment]
if you mean dev branch unstable then no.
version: 0e1e8f6

**Comment by PickleNik** [comment]
note for self:
```
    <v-expand-transition>
      <slot name="reveal"></slot>
    </v-expand-transition>
```
in `dialog-base` needs to be remade like the comment drawer was in 75b5aaf88dbd49b5815c9b1e10c07b9a48f9cc3f
