### ISSUE TITLE
Horizontal scrollbar in settings page

### ISSUE THREAD

**Issue by Mcfly2340** [VueTubeApp/VueTube#270]
### Steps to reproduce

1. Open Vuetube
2. Click on the settings gear at the top right
3. Scroll from right to left

### Expected behavior

There shouldn't be a scrollbar

### Actual behavior

A scrollbar appeared at the bottom of the screen

### VueTube version

F404f12

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to unstable version **[Latest](https://vuetube.app/install/)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 404-Program-not-found** [comment]
hi there, can you attach a video recording of this? And if possible, are you able to share the make and model of your phone?

**Comment by Mcfly2340** [comment]
Yes

**Comment by Mcfly2340** [comment]
https://user-images.githubusercontent.com/71077562/167247880-94c04de8-c690-4eb6-83d9-3eb6743bdd4d.mp4

Make is samsung galaxy Z Flip3
And model is SM-F711B

**Comment by 404-Program-not-found** [comment]
Thank you. I will look into it

**Comment by Robotition** [comment]
This issue has been fixed in the latest commit

**Comment by Mcfly2340** [comment]
Yes, it indeed has been fixed! Thanks!
