### ISSUE TITLE
Change kerning (or font?) of settings, navbar, and search page text.

### ISSUE THREAD

**Issue by afnzmn** [VueTubeApp/VueTube#274]
### Describe your suggested feature

The settings page, navbar, and search pages' font looks bad due to the kerning (or font). Make it match the headers you have elsewhere:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/47723802/168445910-46661ffc-7e9d-47e1-8edd-2d319dee8944.png">
<img width="265" alt="image" src="https://user-images.githubusercontent.com/47723802/168445953-3e0490a5-e2db-4002-bccf-320c2e9a82ac.png">

### Other details

![Screenshot_20220514-151457](https://user-images.githubusercontent.com/47723802/168445880-873bff40-7c86-49c0-b0bb-995004105747.png)
![Screenshot_20220514-153050](https://user-images.githubusercontent.com/47723802/168445884-bf381eb5-a6a0-4ec5-806b-959afbdc950f.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Frontesque** [comment]
as you're saying to put the button text closer together?
