### ISSUE TITLE
[iOS 15.5] Cannot copy public directory

### ISSUE THREAD

**Issue by dreamwhite** [VueTubeApp/VueTube#279]
### Steps to reproduce

1. Clone the repo:
2. cd the cloned repo
3. Install node.js dependencies: `npm i`
4. cd `ios/App`
5. Install cocoapods: `pod install`
6. Open with XCode 13.4 (13F17a) `App.xcworkspace`
7. Change `Signing & Capabilities` with my 7-days Apple Developer Program certificate
8. Build

Actually it complains about not being able to copy `public` directory in `ios/App/App`. Am I missing something?

### Expected behavior

The project building should pass without any problem

### Actual behavior

The build doesn't proceed and gets stuck on `cannot copy public directory`

### VueTube version

1.0

### Android version

iOS 15.5

### Other details

Sorry for my bad english, but I'm not a native speaker.
Below my macOS building environment:

- macOS Monterey 12.4 (21F79)
- XCode 13 (13F71a)
- npm v8.9.0
- node v18.2.0
- pod v1.11.3

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to unstable version **[Latest](https://vuetube.app/install/)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Frontesque** [comment]
i assume that you're talking about the automated ci builds? yea they've started failing for some reason and I'm not exactly sure why. I'll look into that when I can

**Comment by dreamwhite** [comment]
> i assume that you're talking about the automated ci builds? yea they've started failing for some reason and I'm not exactly sure why. I'll look into that when I can

Nope, I'm talking about building the app myself. I don't think there should be differences between automated CI builds and XCode actually 😅

**Comment by Frontesque** [comment]
It turns out that this was an issue with @PickleNik compiling for mac instead of iOS. he will likely be changing this back soon. Please reclone the repo after he pushes the fix.

**Comment by dreamwhite** [comment]
Alright, now I'm having a weird error: `No module named Capacitor`. How can I fix it?

**Comment by 404-Program-not-found** [comment]
> Alright, now I'm having a weird error: `No module named Capacitor`. How can I fix it?

Did you run `npm -i` under both the root and NUXT directory?

**Comment by dreamwhite** [comment]
> > Alright, now I'm having a weird error: `No module named Capacitor`. How can I fix it?
> 
> Did you run `npm -i` under both the root and NUXT directory?

Ouch! I didn't. Gonna update you soon

**Comment by dreamwhite** [comment]
It still blames about `[!] No podspec found for `CapacitorApp` in `..\..\node_modules\@capacitor\app``

**Comment by 404-Program-not-found** [comment]
Don't try to build within the NUXT folder. Build on the root filder

**Comment by dreamwhite** [comment]
I managed to fix it... apparently in Podfile there are `\` instead of `/`. Now it detects Capacitor module but compilation fails while trying to copy `public` directory: 

```
error: /Users/ivan/Desktop/VueTube/ios/App/App/public: No such file or directory 
```

**Comment by dreamwhite** [comment]
Alright, I fixed it! The only thing is that now when I open a video the app crashes. How can I obtain logs?

**Comment by dreamwhite** [comment]
oh okay, i'll let you know. thank you so much again for the effort you're putting on the project :D. I'll close this issue since the "problem" I'm having is way different from the first one.

**Comment by PickleNik** [comment]
> > Alright, I fixed it! The only thing is that now when I open a video the app crashes. How can I obtain logs?
> 
> this is an issue that happens sometimes on iOS as far as we can tell.
> 
> you're also building on node v18 while VueTube is built on node v16. that my fix it.

not sometimes, everytime, it's been like that pretty much since March

**Comment by PickleNik** [comment]
beyond the scope of this issue but just letting you know
