### ISSUE TITLE
Make the default accent color Cyan

### ISSUE THREAD

**Issue by gayolGate** [VueTubeApp/VueTube#305]
### Describe your suggested feature

I think default accent color should be Cyan. It’s the color that identifies VueTube and that its present in the logo, web and Github. It’s very comfortable and relaxing.

### Other details

Just my opinion, please tell me if you agree or disagree

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Frontesque** [comment]
https://github.com/VueTubeApp/VueTube/commit/c0f4386132d0c2e160571bb2a3c7a847bf480a8d
