### ISSUE TITLE
Make element/icon big.

### ISSUE THREAD

**Issue by max5354** [VueTubeApp/VueTube#309]
### Describe your suggested feature

Just one suggestion. Make every element of app big. Like "search icon,library icon,home icon etc. It looks too much small compared to any other apps. Make it average size not tiny.😊

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Frontesque** [comment]
not enough detail given (such as device information)

**Comment by gayolGate** [comment]
> not enough detail given (such as device information)

For my device, the size looks perfectly normal, like in stock YouTube
