### ISSUE TITLE
Weird audio crackling throughout videos

### ISSUE THREAD

**Issue by duckyondiscord** [VueTubeApp/VueTube#312]
### Steps to reproduce

1: Open the app
2: Play ani video for a reasonable amount of time

### Expected behavior

The video and audio should both play without issues

### Actual behavior

The video plays fine but there's a crackling noise throughout the video

### VueTube version

c927557

### Android version

Android 12L

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to unstable version **[Latest](https://vuetube.app/install/)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Frontesque** [comment]
I'm on `Android 12L (12.1)` aswell. What is your devicce make and model? do you mind providing a screenshot from the `about` page within VueTube settings?

**Comment by duckyondiscord** [comment]
> I'm on `Android 12L (12.1)` aswell. What is your devicce make and model? do you mind providing a screenshot from the `about` page within VueTube settings?

It's a OnePlus 6T, and yeah, I'll provide a screenshot.![Screenshot_20220620-115416_VueTube.png](https://user-images.githubusercontent.com/94759537/174564249-a6404d68-f65a-4728-a827-03a99d2355ad.png)

**Comment by max5354** [comment]
> > I'm on `Android 12L (12.1)` aswell. What is your devicce make and model? do you mind providing a screenshot from the `about` page within VueTube settings?
> 
> It's a OnePlus 6T, and yeah, I'll provide a screenshot.![Screenshot_20220620-115416_VueTube.png](https://user-images.githubusercontent.com/94759537/174564249-a6404d68-f65a-4728-a827-03a99d2355ad.png)

Are you using "poweramp equalizer app"?

**Comment by duckyondiscord** [comment]
> > > I'm on `Android 12L (12.1)` aswell. What is your devicce make and model? do you mind providing a screenshot from the `about` page within VueTube settings?
> > 
> > It's a OnePlus 6T, and yeah, I'll provide a screenshot.![Screenshot_20220620-115416_VueTube.png](https://user-images.githubusercontent.com/94759537/174564249-a6404d68-f65a-4728-a827-03a99d2355ad.png)
> 
> Are you using "poweramp equalizer app"?

No, I am not using any sort of audio modifying apps

**Comment by max5354** [comment]
> 

Look i am also have that type of audio cracklings bug. But not in vuetube app. I have that bug on my VLC FOR ANDROID APP and youtube vanced app. I think that happens just because of "poweramp equalizer app" i reported audio cracklings bug to their developers. That's why i asked you "are you using poweramp equalizer app".

**Comment by duckyondiscord** [comment]
Seems to be resolved in the latest version, so I am closing the issue
