### ISSUE TITLE
disable extras

### ISSUE THREAD

**Issue by NSTAdventure** [VueTubeApp/VueTube#314]
### Describe your suggested feature

hi pls consider to allow user disabling extras or any unwanted unnecessary feature
included april fools joke or something like that
thank you for consideration developer 🙏🥴

### Other details

https://t.me/VueTubeChat/841
https://t.me/VueTube/41
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Frontesque** [comment]
please elaborate on what you mean by "extras"

**Comment by NSTAdventure** [comment]
> please elaborate on what you mean by "extras"

extras:
aprill fools and other kind joke feature
easter egg 
and othe additional feature

**Comment by 404-Program-not-found** [comment]
seems rather unnessesary

**Comment by NSTAdventure** [comment]
> seems rather unnessesary

bruh
do you remember the aprill fools release versio?
that is fake notification update?
that causing confusion but ik developer may like to add such feature so instead suggest to remove i suggest to allow user disable those things

that just a example anyway

**Comment by Frontesque** [comment]
what "fake notification update"? there was 1 version released on the discord containing an April fool's joke then the feature was deactivated and removed

**Comment by NSTAdventure** [comment]
> what "fake notification update"? there was 1 version released on the discord containing an April fool's joke then the feature was deactivated and removed

yeah i mean that feature :-/ 
just in case if still exist and if dev add other feature :-/
