### ISSUE TITLE
Add translate Russian for vuetube

### ISSUE THREAD

**Issue by ExtinctDrift19** [VueTubeApp/VueTube#374]
### Describe your suggested feature

Russian language 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by gayolGate** [comment]
You can translate it if you want, [go here](https://github.com/VueTubeApp/VueTube/blob/main/NUXT/plugins/languages/readme.md) and read how

**Comment by Danik2343** [comment]
Translated and opened PR.

**Comment by PickleNik** [comment]
PR merged 👍
Thanks @Danik2343 for the translation.
