### ISSUE TITLE
Option to choose between Unstable and canary updates

### ISSUE THREAD

**Issue by keko999** [VueTubeApp/VueTube#403]
### Describe your suggested feature

A setting where you can choose if you would like to see unstable or canary updates in the Updates tab

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Frontesque** [comment]
GitHub requires account sign in to download the unstable builds. this won't be possible without work arounds
