### ISSUE TITLE
comment section breaks slightly when exiting fullscreen

### ISSUE THREAD

**Issue by starchyunderscore** [VueTubeApp/VueTube#418]
### Steps to reproduce

please reproduce for self as screenshot doesnt show it great

open a video
open comment section
swipe up on video to enter fullscreen
click fullscreen button to exit fullscreen

![Screenshot_20220625-110400_VueTube](https://user-images.githubusercontent.com/102399926/175779481-b79213f3-95a1-4ec9-b85e-dc2b7bcc32ae.jpg)

notice misplaced top section and what looks like a comment stuck at bottom (stays in same place during scroll)

that "comment" is actually the next reccomendation video

### Expected behavior

comment aection should be the same as when you ebtered fullscreen

### Actual behavior

cmomment section breaks slightly

### VueTube version

0.3 (canary)

0.4 (canary)

### Android version

11

### Device

sma102u

### Other details

clicking on video onece afterwards seems to fix issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to unstable version **[Latest](https://vuetube.app/install/)**.
- [X] I will fill out all of the requested information in this form.

**Comment by PickleNik** [comment]
Positioning issue with nav&status bars going away while fullscreened and coming back. Will get resolved when the safeArea margins on Android are figured out and the app launches in fullscreen mode by default.

**Comment by PickleNik** [comment]
fixed in 75b5aaf88dbd49b5815c9b1e10c07b9a48f9cc3f
