### ISSUE TITLE
Comments is not showing in weak network connection

### ISSUE THREAD

**Issue by max5354** [VueTubeApp/VueTube#447]
### Steps to reproduce

Comments is not opening at the starting of video. Look if we have weak network connection and play any video than at the time of buffering if we press comments than suddenly comments tab automatically close and It just show next videos.

### Expected behavior

Open comments.

### Actual behavior

But its not opening comments it's suddenly closes that comments tab. And shows next videos.

### VueTube version

12fe23b

### Android version

Android 10

### Device

Samsung Galaxy j8 2018

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to unstable version **[Latest](https://vuetube.app/install/)**.
- [X] I will fill out all of the requested information in this form.

**Comment by PickleNik** [comment]
dup of #462 ?

**Comment by PickleNik** [comment]
fixed in 75b5aaf88dbd49b5815c9b1e10c07b9a48f9cc3f
