### ISSUE TITLE
"Back" button to exit vuetube is not work with internet off

### ISSUE THREAD

**Issue by max5354** [VueTubeApp/VueTube#453]
### Steps to reproduce

if i open vuetube with off internet and if  i want to exit from vuetube and i press "back" button  but "back" button is not working no matter how many times i pressed it. In short with internet off if i want to exit from app than "back" button is not working no matter how many times i pressed that. So make "back" button to exit vuetube app with off internet connection.

### Expected behavior

To exit from vuetube even with internet off

### Actual behavior

Not exit from vuetube

### VueTube version

4e06619

### Android version

Android 10

### Device

Samsung galaxy j8 2018

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to unstable version **[Latest](https://vuetube.app/install/)**.
- [X] I will fill out all of the requested information in this form.

**Comment by anjannair** [comment]
@max5354 can you please link the correct version. You have linked a random commit instead of your app version.

**Comment by PickleNik** [comment]
it doesn't work on the launch screen because it's only initialized when you get to the home screen

**Comment by PickleNik** [comment]
I'll put it further up in the launch process so that it goes first
