### ISSUE TITLE
Comments is not showing properly 

### ISSUE THREAD

**Issue by max5354** [VueTubeApp/VueTube#462]
https://user-images.githubusercontent.com/90886938/179993452-735f1c22-1a59-454e-9584-707212e86581.mp4

### Steps to reproduce

When we press comments button but it not showing properly. Means comments function not working properly.

### Expected behavior

Comments needs to work properly

### Actual behavior

Comments not showing or not working properly

### VueTube version

96e252a

### Android version

Android 10

### Device

Samsung galaxy j8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to unstable version **[Latest](https://vuetube.app/install/)**.
- [X] I will fill out all of the requested information in this form.

**Comment by PickleNik** [comment]
possible dup of #447 ?

**Comment by PickleNik** [comment]
fixed in 75b5aaf88dbd49b5815c9b1e10c07b9a48f9cc3f
