### ISSUE TITLE
Troll Options for Vuetube: make vuetube have troll options 😲

### ISSUE THREAD

**Issue by gayolGate** [VueTubeApp/VueTube#465]
### Describe your suggested feature

No one YouTube client has troll options. I once tried to make a YT client called YouTube Squid with some secret options, but it was too bad (it used Google API and was made with Appinventor. ah also you couldn't watch videos) so it got cancelled. These are my 21 requests that are neccesary for me (high priority): 

- (1) Dislike Bomb: make videos have 10x more dislikes than likes 😨
- (2) Rickroll: reemplaze all videos with rickroll™ 🥵 (or it is also a copy right infraction?)
- (3) Vuetube is Newpipe: changes the app name to newpipe 🤡
- (4) u famous: App pretends u famous and adds you fake subs 🙄
- (5) Vuegirl: add vuegirl in the app 🥵
- (6) Vuetube is Libretube: the same that vuetube is newpipe but it's libretube instead of newpipe 😜
- (7) genshin impact: app forces you to watch genshin impact videos and if u dont you cant use your phone 🤗
- (8) free netflix: i like youtube but i also like netflix but i dont have money so add free netflix 💀
- (9) return youtube comments: i like return youtube dislike but i also want to see coments when comments are disabled so u add return youtube comments 🏊‍♂️
- (10) Vuetube is Revanced: this doesn't need explanation at this point right? 🚲
- (11) Vuetube is Eclipsed 🏉
- (12) add bots: the same as u famous but its real and it adds you bots, you enter the amount of bots to like and subscribe (example: 56M) and they like and subscribe 😶
- (13) hack: so it allows you to hack another persons videos so for example you clic in edit another guy video and u change title, description, etc. and u have access to his account 😪
- (14) login with geometry dash: so I don't have a google account so it would be cool to login with your geometry dash account 🥶
- (15) go forward in lives: so in youtube you cant go forward in live streamings, it would be cool to have that in vuetube 😲
- (16) change language of videos: i dont like english so if you could change the language of a video to watch in in another language like spanish or polish that would be gret 😉
- (17) comment bomb: commenting on a video again and again so u write one million comments and you have more change of winning a giveaway of fortnite save the world 🐄
- (18) free fortnite: apple its bad because it banned fortnite and stole the money epic used to make amazing updates and care about players  so ban vuetube of apple please (remove all .ipa files) 🧿
- (19) see removed videos: so people remove videos but i want videos so let me be able to still watch them 😢
- (20) no copy: youtube doesnt pay me because i use music in my free robux tutorials so remove copyright 🧐
- (21) more youtube buttons: after the 100M red diamond button add super diamond button (500M), redstone button (1000M), black matter button (2000M), fire button (5000M) and super fire black matter ultra goku redstone button (10000M)

thats all

### Other details

If you implement all these options I will donate 1 euro (1,02 USA dollar at the moment)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by gayolGate** [comment]
Part 2 because you asked tor it 🤯😱🥶

- (22) Puretuber Mode: every time u open the app these is a 50% chance of getting a randomly selected virus 😠
- (23) auto sub to pew de pie: Makes sure vuetube automatically subscribes you to pew de pie because he need to beat tseries 🤔
- (24) Flashlight: flashlight of my phone cant be enabled in top bar and flaslight apps have too ads so pls add a flashlight option in settings 😨
- (25) make app dont use space: i dont have any space because I installed creative destruction so remove all the space that vue tube takes 😇
- (26) YouTube Orange integration: YouTube Orange is a free service that gives a plan B to content creators and protest copyright takedowns in the process. This extension provides you two additional tools on YouTube as a creator:
[fallbackVideo] and [replaceVideo]. If you use the first tool and your video is taken down for any reason, your subscribers and anyone else who has the link and uses YouTube Orange can still view it as if nothing happened. Replace Video is the more robust tool, for when you know you're in the legal green, but Content ID is licking its lips hungrily at you. It allows you to have a video in your users subscriptions, and youtube's search, with full monetization, and absolutely 0 risk of a stike. Upload a placeholder video to youtube, probably explaining to users without Orange what's going on. Then stick a replaceVideo tag in the description! All your users with orange see your vimeo video, right on YouTube, and you are protected from Content ID. (As I said i want to no copyright for my tutorials 😎)
- (27) today is my birth day so make the app give u a gift if its your birth day (example: 1M subs 🤪)
- (28) dont make it dangerous: installing the app my phone warned me vuetube could be dangerous so stop making it dangerous if you havent enabled puretuber mode 😡
- (29) upload it to the Play Store: my school chromecast doesnt allow apk installing so please upload vue tube to play store 🫢
- (30) stardeos compatibility: I like stardeos because its a very serious platform with responsible practices and good promotion that will replace youtube 🤩
![ADA0BB3E-BC02-4EC3-95DD-A3934BFBC2D1](https://user-images.githubusercontent.com/101584172/180164614-f1a7fd50-5591-41f9-aeb9-5092fb797d09.jpeg)

**Comment by KaiAtari** [comment]
This must be a joke right?

**Comment by venkat2305** [comment]
Devs , if you add these, give us an option to disable these (or disable these by default and give an option to enable them).

**Comment by gayolGate** [comment]
> Devs , if you add these, give us an option to disable these (or disable these by default and give an option to enable them).

Its a prank, obviusly they wont get added

**Comment by PickleNik** [comment]
> > Devs , if you add these, give us an option to disable these (or disable these by default and give an option to enable them).
> 
> Its a prank, obviusly they wont get added

Incorrect, these will all be enabled by default when implemented 🔥

**Comment by gayolGate** [comment]
> 

Frontesque disagrees

**Comment by gayolGate** [comment]
> > > Devs , if you add these, give us an option to disable these (or disable these by default and give an option to enable them).
> > 
> > 
> > Its a prank, obviusly they wont get added
> 
> Incorrect, these will all be enabled by default when implemented 🔥

Frontesque disagrees
