### ISSUE TITLE
set the speed for music

### ISSUE THREAD

**Issue by andsofine** [VueTubeApp/VueTube#500]
### Describe your suggested feature

automatically set the standard (or maybe choose that suits you) speed when playing music. sponsorblock can determine where the music is.

I watch all the videos on 1.5 and it's not very convenient when the music is played at the same speed

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by PickleNik** [comment]
Dup of #474

**Comment by Frontesque** [comment]
duplicate
