### ISSUE TITLE
versionCode is never increased

### ISSUE THREAD

**Issue by IzzySoft** [VueTubeApp/VueTube#535]
### Steps to reproduce

Just run `aapt d badging VueTube-Canary-0.4.2.apk` to see it's still set to `1`:

    package: name='com.Frontesque.vuetube' versionCode='1' versionName='0.4.2' compileSdkVersion='30' compileSdkVersionCodename='11'

### Expected behavior

`versionCode` is increased with each release, so Android considers the new APK being an update to the installed app.

### Actual behavior

No update notification as Android considers the new APK being the same version.

### VueTube version

0.4.2

### Android version

Android 11

### Device

all

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to unstable version **[Latest](https://vuetube.app/install/)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Frontesque** [comment]
The version code will be incremented once we hit version `1.0`.

**Comment by IzzySoft** [comment]
Thanks – but why not starting now? Without that, those who prefer using an F-Droid client to manage their apps (VueTube is [available here](https://apt.izzysoft.de/fdroid/index/apk/com.Frontesque.vuetube)) will never receive update notifications before you reach 1.0 – and each update in the repo would overwrite the previous version (instead of multiple versions being available). As pointed out, `versionCode` is what Android uses to tell versions apart, so it's crucial to increase that whenever propagating a new version.

Just wondering and suggesting – I will of course respect your decision.

**Comment by Frontesque** [comment]
I didn't build the latest version. My life has been too crazy to work on this and it seems like the rest of the team that was working on it has stopped.

**Comment by IzzySoft** [comment]
Ouch… So who has the signing keys? Can you build & sign (and will you)? No pressure, I just want to figure how to continue.
