### ISSUE TITLE
User Submitted Tranlations

### ISSUE THREAD

**Issue by zicraftian** [VueTubeApp/VueTube#538]
### Describe your suggested feature

It would be great to have the user submitted translation feature re-implemented back, since YouTube removed it.

### Other details

It would work exactly as the old YouTube feature worked

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by gayolGate** [comment]
Probably it won't be implemented because that requires the creation a database and isn't on the scope of VueTube

**Comment by 404-Program-not-found** [comment]
This feature idea is not within the scope of VueTube
