### ISSUE TITLE
Video displaying "The following content is not available..."

### ISSUE THREAD

**Issue by musabninja** [VueTubeApp/VueTube#570]
### Steps to reproduce

Open any video
The message is displayed

### Expected behavior

The video is playable

### Actual behavior

The video is unplayable

### VueTube version

0.4.2

### Android version

Android 12

### Device

Xiaomi Mi 10 

### Other details

![Screenshot_2022-10-29-18-59-13-671_com Frontesque vuetube](https://user-images.githubusercontent.com/87612518/198846293-86830258-f7a2-4d59-8353-d312fe152004.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to unstable version **[Latest](https://vuetube.app/install/)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 404-Program-not-found** [comment]
Can you post the link you are trying to access?

**Comment by musabninja** [comment]
> Can you post the link you are trying to access?

It does it in all the videos
