### ISSUE TITLE
comment section does not open

### ISSUE THREAD

**Issue by starchyunderscore** [VueTubeApp/VueTube#581]
### Steps to reproduce

1. open vuetube 0.5 (canary)
2. open a video
3. click comments button

### Expected behavior

comments section opens

### Actual behavior

comment section shows for split second before closing, showing recommended videos again
you cannot scroll through recommended videos until you hit the back button, at which point the comment section shows again briefly before closing

### VueTube version

0.5 (canary)

### Android version

android 11

### Device

SM-A102U

### Other details

https://user-images.githubusercontent.com/102399926/202338330-6fb2ffb5-6835-49b0-894c-72f95cb463f6.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to unstable version **[Latest](https://vuetube.app/install/)**.
- [X] I will fill out all of the requested information in this form.

**Comment by starchyunderscore** [comment]
i also dont know about #462 because that video does not work so I cant see the bug

**Comment by starchyunderscore** [comment]
ok yea its a dupe of #462 the vid loads now an a difeerent device. closing.

**Comment by PickleNik** [comment]
(fixed in 75b5aaf88dbd49b5815c9b1e10c07b9a48f9cc3f)
