### ISSUE TITLE
New design for Home, Subscription and library buttons

### ISSUE THREAD

**Issue by tvnmguy** [VueTubeApp/VueTube#584]
### Describe your suggested feature

Current Home, Subscriptions, and Library icons feels so old and outdated.

I'm serving some suggestions here;

By default;

![IMG_20221128_125900](https://user-images.githubusercontent.com/116799295/204251832-bc31af76-2be3-4960-a79b-664529eadaa7.jpg)

When enabling Round Watch Page Component from settings then icons background changes to long round border with selected accent colour.

![img_2022_11_28_15_22_10](https://user-images.githubusercontent.com/116799295/204250052-ece78515-6118-400c-8948-f66e5db58bea.jpg)

### Other details

The texts below to the icons are removed because there is already tab name exist top left corner.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by PickleNik** [comment]
@tvnmguy what's the iconset?

**Comment by PickleNik** [comment]
I think it's Fluent icons, but I can't find the last 2

**Comment by tvnmguy** [comment]
> I think it's Fluent icons, but I can't find the last 2

The buttons are inspired from Spotify mobile app.

https://user-images.githubusercontent.com/116799295/209605274-b3e32429-4f05-4a27-8328-b4067fc94465.mp4

The 2nd button (subscription button) created from the 3rd library button, so its hard to find.

Sorry, I don't have the svg files because the pictures edited throughout mobile editor app.

**Comment by PickleNik** [comment]
cool, I'll just add some options from common icon sets, option to hide text already done btw 
![image](https://user-images.githubusercontent.com/31113245/209607397-d4989446-0ad5-4480-a2cc-e881f36b9971.png)

**Comment by tvnmguy** [comment]
@PickleNik 

Awesome💥
