### ISSUE TITLE
"Subscribe" button doesn't say "Subscribed" even after subscribing.

### ISSUE THREAD

**Issue by Octopus1348** [VueTubeApp/VueTube#586]
### Steps to reproduce

1. Search up the channel you want to subscribe.
2. Click on the channel.
3. Click subscribe.

### Expected behavior

I'm pretty sure it should say "Subscribed".

### Actual behavior

It DOES subscribe, but it doesn't say "Subscribed" under that channel.

### VueTube version

e02ecb2

### Android version

Android 12

### Device

Samsung Galaxy Tab A 10.1 running LineageOS

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to unstable version **[Latest](https://vuetube.app/install/)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 404-Program-not-found** [comment]
Subscribing isn't a feature at the moment

**Comment by Octopus1348** [comment]
> Subscribing isn't a feature at the moment

Then it's starting to become one, because as I said, when clicking the subscribe button, then you will see the creator's videos you subscribed to in your home.
