### ISSUE TITLE
Allow ads on specific channels with a click of a button

### ISSUE THREAD

**Issue by HiroDane** [VueTubeApp/VueTube#60]
I envision something like a Subscribe button which would allow to activate ads for a specific channel so that good creators can still earn through ad revenues. This would probably work much like AdBlock's option to add channel specific ads but with a better UI. Here is the adblock version for reference: 
![adblockexample](https://user-images.githubusercontent.com/20228557/158578410-2428bb83-b86c-425a-b0d8-497d2d8c36b4.png)

What I envsion is something like this:

![allowads_LI](https://user-images.githubusercontent.com/20228557/158579540-ed5ccf09-3eb6-4f1d-a503-78e3571d3ff9.jpg)

**Comment by 404-Program-not-found** [comment]
Youtube video ad integration is a far too challenging task with no way to confirm that a user's watch time is actually being recorded instead of time simply being wasted. It also does not bring much to the table in terms of benefits. This feature will not be worked on for the foreseeable future.
