### ISSUE TITLE
Sharing video link with timestamps

### ISSUE THREAD

**Issue by ToTheMoon1234** [VueTubeApp/VueTube#72]
An option to share the link of video with the timestamps you are at the moment in the video instead of the regular link. 
So that when someone opens the timestamped link, the video starts playing from the timestamp instead of the beginning

**Comment by Harmonie666** [comment]
Yes Vanced had this. Would be nice to have it in VT.

**Comment by 404-Program-not-found** [comment]
It should be as simple as getting the current timestamp and just appending it to a youtu.be link. Looks good, will implement when I get the time

**Comment by 404-Program-not-found** [comment]
closing issue as it has been implemented
