### ISSUE TITLE
Search button improvements

### ISSUE THREAD

**Issue by uzamapg** [VueTubeApp/VueTube#89]
**Is your feature request related to a problem? Please describe.**
As it is in vanilla Youtube app, you can tap the search icon and the keyboard opens up immediately. But in current VueTube builds, you have to tap the search icon then tap the text box again in order to show the keyboard and start typing your queries.

**Describe the solution you'd like**
Tapping the search button should instantly open the keyboard letting you start searching right away.

**Describe alternatives you've considered**
none.

**Additional context**
none.

**Comment by PickleNik** [comment]
done already, forgor to close
